//! Generation of documentation owned by the conformance model.

use core::fmt::Write as _;

use crate::Model;

/// Committed generated conformance path.
pub const CONFORMANCE_PATH: &str = "CONFORMANCE.md";

/// Renders `CONFORMANCE.md` from the model.
pub fn render_conformance(model: &Model) -> String {
    let mut output = String::new();
    let writer = &mut output;
    let _ = writeln!(
        writer,
        "<!-- @generated by `cargo xtask check-model --write` from model/*.toml. -->"
    );
    let _ = writeln!(
        writer,
        "<!-- Do not edit. The model is the single source. -->"
    );
    let _ = writeln!(writer);
    let _ = writeln!(writer, "# CONFORMANCE");
    let _ = writeln!(writer);
    let _ = writeln!(
        writer,
        "Every registered ID has a Gherkin scenario and a test whose name ends in its"
    );
    let _ = writeln!(writer, "lowercased ID.");
    let _ = writeln!(writer);
    let _ = writeln!(writer, "| Level | Meaning |");
    let _ = writeln!(writer, "| --- | --- |");
    let _ = writeln!(
        writer,
        "| `some-true` | Reproduced from a cited authority; not established here. |"
    );
    let _ = writeln!(
        writer,
        "| `build` | Constructed here and validated against a local oracle. |"
    );
    let _ = writeln!(
        writer,
        "| `open` | Measured and reported without a universal assertion. |"
    );

    let mut suites: Vec<&str> = model.ids.id.iter().map(|row| row.suite.as_str()).collect();
    suites.sort_unstable();
    suites.dedup();

    for suite in suites {
        let rows: Vec<_> = model
            .ids
            .id
            .iter()
            .filter(|row| row.suite == suite)
            .collect();
        if rows.is_empty() {
            continue;
        }
        let _ = writeln!(writer);
        let _ = writeln!(writer, "## {suite}");
        let _ = writeln!(writer);
        let _ = writeln!(writer, "| ID | Level | Statement |");
        let _ = writeln!(writer, "| --- | --- | --- |");
        for row in rows {
            let statement = row.statement.replace('\n', " ").replace('|', "\\|");
            let _ = writeln!(
                writer,
                "| `{}` | `{}` | {} |",
                row.id,
                row.level.as_str(),
                statement.trim()
            );
        }
    }

    let _ = writeln!(writer);
    let _ = writeln!(writer, "## Cited authorities");
    let _ = writeln!(writer);
    let _ = writeln!(writer, "| Authority | Citation | Local evidence |");
    let _ = writeln!(writer, "| --- | --- | --- |");
    for authority in &model.authorities.authority {
        let citation = authority.citation.replace('\n', " ").replace('|', "\\|");
        let realized = if authority.realized_by.is_empty() {
            "--".to_string()
        } else {
            authority
                .realized_by
                .iter()
                .map(|id| format!("`{id}`"))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let _ = writeln!(
            writer,
            "| `{}` | {} | {realized} |",
            authority.id,
            citation.trim()
        );
    }

    let _ = writeln!(writer);
    let _ = writeln!(writer, "## Claims that are not conformance IDs");
    let _ = writeln!(writer);
    let _ = writeln!(writer, "| ID | Level | Claim |");
    let _ = writeln!(writer, "| --- | --- | --- |");
    for claim in &model.ledger.claim {
        let statement = claim.statement.replace('\n', " ").replace('|', "\\|");
        let _ = writeln!(
            writer,
            "| `{}` | `{}` | {} |",
            claim.id,
            claim.level.as_str(),
            statement.trim()
        );
    }

    output
}
